<?php

/**
 * Implements hook_preprocess_HOOK() for weather_page.html.twig.
 */
function anytown_preprocess_weather_page(array &$variables)
{
    // Récupérer le service path.matcher
    $path_matcher = \Drupal::service('path.matcher');

    // Créer la variable is_front
    $variables['is_front'] = $path_matcher->isFrontPage();
}

function anytown_page_attachments_alter(array &$attachments)
{
    // Ajouter une balise meta pour le viewport
    $attachments['#attached']['html_head'][] = [
        [
            '#tag' => 'meta',
            '#attributes' => [
                'name' => 'viewport',
                'content' => 'width=device-width, initial-scale=1, shrink-to-fit=no',
            ],
        ],
        'anytown_viewport_meta',
    ];
}

/**
 * Implements hook_preprocess_menu().
 */

function anytown_preprocess_menu(array &$variables)
{
    // Vérifie que le tableau contient des items
    if (isset($variables['items']) && is_array($variables['items'])) {
        foreach ($variables['items'] as &$item) {
            // Ajoute la classe CSS à chaque lien du menu
            if (!isset($item['attributes'])) {
                $item['attributes'] = [];
            }
            if (!isset($item['attributes']['class'])) {
                $item['attributes']['class'] = [];
            }
            $item['attributes']['class'][] = 'my-custom-class';
        }
    }
}


/**
 * Implements hook_preprocess_block().
 */
function anytown_preprocess_block(array &$variables)
{

    if ($variables['plugin_id'] === 'system_branding_block') {

        $variables['site_logo'] = 'https://static.cdnlogo.com/logos/d/88/drupal-wordmark.svg';

        if (isset($variables['content']['site_logo'])) {
            $variables['content']['site_logo']['#uri'] =
                'https://static.cdnlogo.com/logos/d/88/drupal-wordmark.svg';
        }
    }
}
